### ISSUE TITLE
为何专业版仅提供远程技术支持，铂金版“可独立购买咨询服务”

### ISSUE THREAD

**Issue by husterindg88** [huaweicloudDocs/cpts#1]
https://support.huaweicloud.com/usermanual-cpts/cpts_01_0002.html
技术支持这一栏，建议说清楚：1.铂金版是否可以享受远程技术支持；2.专业版为啥不能花钱购买咨询服务。

**Comment by Hupch** [comment]
目前铂金版和专业版一样，都支持远程技术支持，文档中删除技术支持这一栏。
